# Jekyll configuration

name: Qooqle
description:

baseurl: lijiangming.com

permalink: /:year/:month/:day/:title
paginate: 50

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']
