# Jekyll configuration

name: Qooqle
description:

baseurl: ""

permalink: /:year/:month/:day/:title
paginate: 50

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: ['jekyll-paginate']

plugins:
  - jekyll-sitemap

exclude: ['README.md', 'LICENSE', 'CNAME']
